import React from 'react';
import './LegalPages.css';

function TermsAndConditionsPage() {
    return (
        <div className="App-container">
            <div className="legal-container">
                <h1>Terms & Conditions</h1>
                <p><strong>Last Updated:</strong> July 17, 2025</p>

                <h2>1. Agreement to Terms</h2>
                <p>By accessing or using our website and services (the "Service"), you agree to be bound by these Terms & Conditions. If you do not agree with any part of these terms, you may not use our Service.</p>
                
                <h2>2. Use of the Service</h2>
                <ul>
                    <li>You must create an account to access the core features of the Service.</li>
                    <li>You agree to provide accurate and complete information when you create an account.</li>
                    <li>You are responsible for maintaining the confidentiality of your account and password.</li>
                    <li>You agree not to use the Service for any unlawful purpose or to solicit others to perform or participate in any unlawful acts.</li>
                </ul>

                <h2>3. Itineraries and Generated Content</h2>
                <p>
                    The itineraries and suggestions provided by Cabito are generated by an AI and are for informational and planning purposes only. They are based on data from public sources and third-party services.
                </p>
                <p>
                    <strong>Disclaimer:</strong> Cabito does not guarantee the accuracy of any information, including but not limited to opening hours, travel times, costs, or the suitability of any location. Real-world conditions can change rapidly. You are solely responsible for your own safety, verifying all information before your trip, and making your own decisions. Cabito is not liable for any issues, damages, or losses that may occur during your travels.
                </p>

                <h2>4. Intellectual Property</h2>
                <p>The Service and its original content, features, and functionality are and will remain the exclusive property of Cabito and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without our prior written consent.</p>

                <h2>5. Termination</h2>
                <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms.</p>

                <h2>6. Limitation of Liability</h2>
                <p>In no event shall Cabito, nor its directors, employees, or partners, be liable for any indirect, incidental, special, consequential or punitive damages resulting from your access to or use of, or inability to access or use, the Service.</p>

                <h2>7. Governing Law</h2>
                <p>These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction, e.g., India], without regard to its conflict of law provisions.</p>

                <h2>8. Changes to Terms</h2>
                <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.</p>
                
                <h2>9. Contact Us</h2>
                <p>If you have any questions about these Terms, please contact us at <a href="mailto:support@cabito.co.in">support@cabito.co.in</a>.</p>

            </div>
        </div>
    );
}

export default TermsAndConditionsPage;